behaviors:
  MovingBrainSac:
    trainer_type: sac
    hyperparameters:
      batch_size: 512
      buffer_size: 50000
      learning_rate: 3.0e-4
      learning_rate_schedule: linear      
      buffer_init_steps: 1000
      tau: 0.005
      steps_per_update: 10.0
      save_replay_buffer: false
      init_entcoef: 0.8
      reward_signal_steps_per_update: 10.0     
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 1500000
    time_horizon: 64
    summary_freq: 10000